# Generated by Django 5.2.17 on 2026-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.BooleanField(default=True),
        ),
    ]
